### ISSUE TITLE
The package is empty

### ISSUE THREAD

**Issue by patriziobrunops** [simenandre/firestore-graphql-scalars#310]
The package on npmjs.com is empty. The build log confirms it 
https://github.com/simenandre/firestore-graphql-scalars/actions/runs/4805748867/jobs/8552476094#step:8:11

**Comment by simenandre** [comment]
Haha! That is fun!

Let me have a look

**Comment by simenandre** [comment]
Fixed in https://github.com/simenandre/firestore-graphql-scalars/releases/tag/v3.0.1

**Comment by simenandre** [comment]
It seems the issues have been resolved:
https://www.runpkg.com/?firestore-graphql-scalars@3.0.1/dist/src/main.js
